export const SKILL_LEVELS = ['Junior', 'Middle', 'Senior']
export const WORK_TYPES = ['Remote', 'Fulltime', 'Parttime']
export const SKILLS = [
    'Web-Design',
    'Design',
    'Adobe',
    'Adobe Acrobat',
    'Adobe Illustrator',
    'Adobe InDesign',
    'Adobe Photoshop',
    'C++',
    'CSS',
    'Data Analysis',
    'Django',
    'Django Framework',
    'Django REST Framework',
    'Docker',
    'Flask',
    'Git',
    'Github',
    'HTML',
    'JavaScript',
    'Jupyter Notebook',
    'Linux',
    'MS PowerPoint',
    'PostgreSQL',
    'Python',
    'SketchUp',
    'SOLID',
    'SQL',
    'SQLAlchemy',
    'SQLite',
    'SVN',
    'V-Ray',
    'Web Design',
];
