export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
export const AUTHENTICATION_SUCCEED = 'AUTHENTICATION_SUCCEED';
export const GET_CURRENT_USERNAME = 'GET_CURRENT_USERNAME';
export const LOGOUT = 'LOGOUT';
